// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYiBGhUb1vaMxR8dCQj7Pkl3ynRNVkq74',
    appId: '1:940242670367:web:86abca1561cac8c4ac162a',
    messagingSenderId: '940242670367',
    projectId: 'chat-app-d86a7',
    authDomain: 'chat-app-d86a7.firebaseapp.com',
    databaseURL: 'https://chat-app-d86a7-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-d86a7.appspot.com',
    measurementId: 'G-N0MVZG6JYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfmMVht41CBwgZJFNGM1dPW4jJp_pAbJI',
    appId: '1:940242670367:android:2549faec03b0f6c1ac162a',
    messagingSenderId: '940242670367',
    projectId: 'chat-app-d86a7',
    databaseURL: 'https://chat-app-d86a7-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-d86a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmAvBp5wMbVgGteQSUpFB9KQG1egvErwc',
    appId: '1:940242670367:ios:b195c8d7536b6351ac162a',
    messagingSenderId: '940242670367',
    projectId: 'chat-app-d86a7',
    databaseURL: 'https://chat-app-d86a7-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-d86a7.appspot.com',
    iosBundleId: 'com.example.votex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmAvBp5wMbVgGteQSUpFB9KQG1egvErwc',
    appId: '1:940242670367:ios:b195c8d7536b6351ac162a',
    messagingSenderId: '940242670367',
    projectId: 'chat-app-d86a7',
    databaseURL: 'https://chat-app-d86a7-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-d86a7.appspot.com',
    iosBundleId: 'com.example.votex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYiBGhUb1vaMxR8dCQj7Pkl3ynRNVkq74',
    appId: '1:940242670367:web:ae5cf16aa6a71fa5ac162a',
    messagingSenderId: '940242670367',
    projectId: 'chat-app-d86a7',
    authDomain: 'chat-app-d86a7.firebaseapp.com',
    databaseURL: 'https://chat-app-d86a7-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-d86a7.appspot.com',
    measurementId: 'G-PCM8TT5BSR',
  );
}
